### ISSUE TITLE
Can't send invites

### ISSUE THREAD

**Issue by SCRN-VRC** [ScruffyRules/OmissionCorkAngry#1]
https://cdn.discordapp.com/attachments/624090376755740673/722828798558732289/unknown.png
![issue](https://user-images.githubusercontent.com/49093147/84915526-7b44cc00-b0ef-11ea-8983-5d834a0bc93e.png)

**Comment by ScruffyRules** [comment]
Fixed by 9366574a7c935a00e1670807291d745c60fe2eb2
